### ISSUE TITLE
Quantize glm-4v-9b with INT8 Quantization

### ISSUE THREAD

**Issue by citrix123** [vllm-project/llm-compressor#1003]
**Describe the bug**
Trying to Qunatize glm-4v-9b with INT8 Qunatization
Tried to follow https://docs.vllm.ai/en/latest/quantization/int8.html Example , But it seems to be for Instruct Model and not for MultiModel.

**Expected behavior**
it should be Qunatized by using ShareGPTV4 Dataset.

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 20.04]: Ubuntu 22.04
2. Python version [e.g. 3.7]: 3.10
3. LLM Compressor version or commit hash [e.g. 0.1.0, `f7245c8`]: 0.3.1
4. ML framework version(s) [e.g. torch 2.3.1]: 2.5.1+gitabbfe77
5. Other Python package versions [e.g. vLLM, compressed-tensors, numpy, ONNX]: vLLM
6. Other relevant environment information [e.g. hardware, CUDA version]: AMD W7900 with Rocm 6.3

**To Reproduce**
Exact steps to reproduce the behavior:
Tried to use Example as here - https://docs.vllm.ai/en/latest/quantization/int8.html

But seems its for Instruct Based model, Below is the script i was trying.

``` py
from transformers import AutoProcessor, GlmForCausalLM
from llmcompressor.transformers import oneshot
from llmcompressor.modifiers.quantization import GPTQModifier
from llmcompressor.modifiers.smoothquant import SmoothQuantModifier

MODEL_ID = "/model/glm-4v-9b"
model = GlmForCausalLM.from_pretrained(
    MODEL_ID, device_map="auto", torch_dtype="auto", trust_remote_code=True
)
tokenizer = AutoProcessor.from_pretrained(MODEL_ID, trust_remote_code=True)

from datasets import load_dataset

NUM_CALIBRATION_SAMPLES = 512
MAX_SEQUENCE_LENGTH = 2048

ds = load_dataset("/model/ShareGPT4V-dataset", 'ShareGPT4V', split="train")
ds = ds.shuffle(seed=42)
ds = ds.select(range(NUM_CALIBRATION_SAMPLES))

# Configure the quantization algorithms
recipe = [
    SmoothQuantModifier(smoothing_strength=0.8),
    GPTQModifier(targets="Linear", scheme="W8A8", ignore=["lm_head"]),
]

# Apply quantization
oneshot(
    model=model,
    dataset=ds,
    recipe=recipe,
    max_seq_length=MAX_SEQUENCE_LENGTH,
    num_calibration_samples=NUM_CALIBRATION_SAMPLES,
    trust_remote_code_model=True
)
```

**Errors**
```
Traceback (most recent call last):
  File "/model/glm-4v/quan_experiments/quant-glm4v-int8.py", line 28, in <module>
    oneshot(
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/llmcompressor/transformers/finetune/text_generation.py", line 82, in oneshot
    main(model_args, data_args, training_args)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/llmcompressor/transformers/finetune/text_generation.py", line 333, in main
    stage_runner.populate_datasets(tokenizer=tokenizer, add_labels=add_labels)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/llmcompressor/transformers/finetune/runner.py", line 115, in populate_datasets
    tokenized_dataset = dataset_manager.tokenize_and_process(
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/llmcompressor/transformers/finetune/data/base.py", line 161, in tokenize_and_process
    dataset = self.map(
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/llmcompressor/transformers/finetune/data/base.py", line 229, in map
    return dataset.map(**kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 560, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2971, in map
    return self.remove_columns(remove_columns)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 560, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/datasets/fingerprint.py", line 442, in wrapper
    out = func(dataset, *args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2164, in remove_columns
    raise ValueError(
ValueError: Column name ['text'] not in the dataset. Current columns in the dataset: []
```

**Additional context**
Not very sure if the Script is correct or dataset can be used in this way for MultiModel. Please help, Thanks.

**Comment by robertgshaw2-neuralmagic** [comment]
Hey @kylesayrs - are any of the new multimodal pathways ready for trialing?

**Comment by kylesayrs** [comment]
Hi @citrix123! You can now quantize ChatGLM by checking out the `kylesayrs/gptq-partition` branch and running the script below. Full support for this VLM and others will be a part of the next llm-compressor release.

Please let me know if this script works for your use case!

<details><summary>glm_example.py</summary>
```
import requests
from PIL import Image
from io import BytesIO

from transformers import AutoProcessor
from llmcompressor.transformers import oneshot
from llmcompressor.modifiers.quantization import GPTQModifier
from datasets import load_dataset
from llmcompressor.transformers.tracing import ChatGLMForConditionalGeneration

from llmcompressor.transformers.utils.data_collator import glm_data_collator

MODEL_ID = "THUDM/glm-4v-9b"
model = ChatGLMForConditionalGeneration.from_pretrained(
    MODEL_ID, device_map="auto", torch_dtype="auto", trust_remote_code=True
)
processor = AutoProcessor.from_pretrained(MODEL_ID, trust_remote_code=True)

NUM_CALIBRATION_SAMPLES = 512
MAX_SEQUENCE_LENGTH = 2048

ds = load_dataset("Lin-Chen/ShareGPT4V", "ShareGPT4V", split=f"train[:{NUM_CALIBRATION_SAMPLES}]")
ds = ds.shuffle(seed=42)

def preprocess(example):
    url_part = "/".join(example["image"].split("/")[1:])
    url = f"http://images.cocodataset.org/{url_part}"
    response = requests.get(url)
    response.raise_for_status()
    image = Image.open(BytesIO(response.content)).convert('RGB')

    return processor.apply_chat_template(
        [
            {
                "role": "user",
                "image": image,
                "content": example["conversations"][0]["value"],
            }
        ],
        add_generation_prompt=True,
        tokenize=True,
        return_tensors="pt",
        return_dict=True,
    )


ds = ds.map(preprocess, remove_columns=ds.column_names)

# Configure the quantization algorithms
recipe = [
    GPTQModifier(
        targets="Linear",
        scheme="W8A8",
        sequential_targets=["GLMBlock"],
        ignore=["transformer.output_layer", "re:transformer.vision.*"],
    ),
]

# Apply quantization
oneshot(
    model=model,
    dataset=ds,
    recipe=recipe,
    max_seq_length=MAX_SEQUENCE_LENGTH,
    num_calibration_samples=NUM_CALIBRATION_SAMPLES,
    trust_remote_code_model=True,
    data_collator=glm_data_collator,
)
```
</details>

**Comment by citrix123** [comment]
Hi @kylesayrs , Thanks for the script and information !

It worked and ran for a about ~3 hours but than I hit the error.

``` sh
/model/llm-compressor/src/llmcompressor/modifiers/quantization/gptq/base.py:248: UserWarning: ChatGLMForConditionalGeneration fails layer-wise assumptions
  warnings.warn(f"{model_name} fails layer-wise assumptions")
/model/llm-compressor/src/llmcompressor/modifiers/quantization/gptq/base.py:252: UserWarning: Falling back to basic pipeline, which requires extra memory and
may result in decreased accuracy
  warnings.warn(
Calibrating:   0%|                                     | 0/512 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "/model/llm-compressor/src/llmcompressor/modifiers/quantization/gptq/utils/gptq_quantize.py", line 161, in quantize_weight
    H = torch.linalg.cholesky(H)
torch._C._LinAlgError: linalg.cholesky: The factorization could not be completed because the input is not positive-definite (the leading minor of order 8834 i
s not positive-definite).
```
Please find the Traceback below, I am using [compressed-tensors](https://github.com/neuralmagic/compressed-tensors) latest commit, because 0.8.1 version dont have `update_offload_parameter`
Please let me know if i am doing something wrong in here ! Thanks 

<details>
<summary> Traceback  </summary>

``` sh
Traceback (most recent call last):
  File "/model/llm-compressor/src/llmcompressor/modifiers/quantization/gptq/base.py", line 221, in on_initialize
    run_sequential(
  File "/model/llm-compressor/src/llmcompressor/pipelines/sequential/pipeline.py", line 64, in run_pipeline
    forward_function(model, **inputs)
  File "<string>", line 7, in forward
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/model/llm-compressor/src/llmcompressor/transformers/tracing/glm/modeling_chatglm.py", line 711, in forward
    mlp_output = self.mlp(layernorm_output)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/model/llm-compressor/src/llmcompressor/transformers/tracing/glm/modeling_chatglm.py", line 647, in forward
    output = self.dense_4h_to_h(intermediate_parallel)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1844, in _call_impl
    return inner()
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1803, in inner
    hook_result = hook(self, args, result)
  File "/model/llm-compressor/src/llmcompressor/modifiers/utils/hooks.py", line 69, in wrapped_hook
    return hook(*args, **kwargs)
  File "/model/llm-compressor/src/llmcompressor/modifiers/quantization/gptq/base.py", line 319, in compress_module
    loss, quantized_weight, scale, zero_point, g_idx = quantize_weight(
  File "/model/llm-compressor/src/llmcompressor/modifiers/quantization/gptq/utils/gptq_quantize.py", line 166, in quantize_weight
    raise ValueError(
ValueError: Failed to invert hessian due to numerical instability. Consider increasing GPTQModifier.dampening_frac, increasing the number of calibration samples, or shuffling the calibration dataset

```

``` sh
Traceback (most recent call last):
  File "/model/llm-compressor/src/llmcompressor/modifiers/quantization/gptq/base.py", line 238, in on_initialize
    run_layer_sequential(
  File "/model/llm-compressor/src/llmcompressor/pipelines/layer_sequential/pipeline.py", line 56, in run_pipeline
    layer(**inputs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: GLMBlock.forward() missing 1 required positional argument: 'rotary_pos_emb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/model/glm-4v/quan_experiments/quant-glm4v-int8-community.py", line 62, in <module>
    oneshot(
  File "/model/llm-compressor/src/llmcompressor/transformers/finetune/text_generation.py", line 84, in oneshot
    main(model_args, data_args, training_args)
  File "/model/llm-compressor/src/llmcompressor/transformers/finetune/text_generation.py", line 413, in main
    stage_runner.one_shot()
  File "/model/llm-compressor/src/llmcompressor/transformers/finetune/runner.py", line 163, in one_shot
    self.trainer.one_shot(calibration_data=calib_data, stage=stage)
  File "/model/llm-compressor/src/llmcompressor/transformers/finetune/session_mixin.py", line 440, in one_shot
    apply(
  File "/model/llm-compressor/src/llmcompressor/core/session_functions.py", line 184, in apply
    return active_session().apply(
  File "/model/llm-compressor/src/llmcompressor/core/session.py", line 212, in apply
    self.initialize(**kwargs)
  File "/model/llm-compressor/src/llmcompressor/core/session.py", line 158, in initialize
    mod_data = self._lifecycle.initialize(
  File "/model/llm-compressor/src/llmcompressor/core/lifecycle.py", line 126, in initialize
    data = mod.initialize(state=self.state, **extras)
  File "/model/llm-compressor/src/llmcompressor/modifiers/stage.py", line 124, in initialize
    modifier.initialize(state, **kwargs)
  File "/model/llm-compressor/src/llmcompressor/modifiers/modifier.py", line 118, in initialize
    initialized = self.on_initialize(state=state, **kwargs)
  File "/model/llm-compressor/src/llmcompressor/modifiers/quantization/gptq/base.py", line 256, in on_initialize
    run_basic(state.model, state.data.calib)
  File "/model/llm-compressor/src/llmcompressor/pipelines/basic/pipeline.py", line 20, in run_pipeline
    model(**batch)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/model/llm-compressor/src/llmcompressor/transformers/tracing/glm/modeling_chatglm.py", line 1179, in forward
    transformer_outputs = self.transformer(
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
File "/model/llm-compressor/src/llmcompressor/transformers/tracing/glm/modeling_chatglm.py", line 1179, in forward
    transformer_outputs = self.transformer(
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/model/llm-compressor/src/llmcompressor/transformers/tracing/glm/modeling_chatglm.py", line 1049, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/model/llm-compressor/src/llmcompressor/transformers/tracing/glm/modeling_chatglm.py", line 787, in forward
    layer_ret = layer(
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/model/llm-compressor/src/llmcompressor/transformers/tracing/glm/modeling_chatglm.py", line 711, in forward
    mlp_output = self.mlp(layernorm_output)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/model/llm-compressor/src/llmcompressor/transformers/tracing/glm/modeling_chatglm.py", line 647, in forward
    output = self.dense_4h_to_h(intermediate_parallel)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1844, in _call_impl
    return inner()
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1803, in inner
    hook_result = hook(self, args, result)
  File "/model/llm-compressor/src/llmcompressor/modifiers/utils/hooks.py", line 69, in wrapped_hook
    return hook(*args, **kwargs)
  File "/model/llm-compressor/src/llmcompressor/modifiers/quantization/gptq/base.py", line 306, in compress_module
    self._hessians[module],
KeyError: Linear(in_features=13696, out_features=4096, bias=False)
```
</details>

**Comment by kylesayrs** [comment]
Hi @citrix123,

The `torch._C._LinAlgError` can occur due to numerical instability in the GPTQ algorithm. This can be solved by shuffling your dataset. If you try a few seeds and that doesn't work, you can increase the `GPTQModifier.dampening_frac` parameter, although you may seem slightly decreased performance if it comes to this.
```
except torch._C._LinAlgError:
    raise ValueError(
        "Failed to invert hessian due to numerical instability. Consider "
        "increasing GPTQModifier.dampening_frac, increasing the number "
        "of calibration samples, or shuffling the calibration dataset"
    )
```

**Comment by citrix123** [comment]
Hi @kylesayrs 

Thanks for the guidence :)

It worked perfectly, But when i tried adding below 2 lines to save the model. It got killed due to OOM.
do you see the same behaviour at your side ?

``` python
# Apply quantization
oneshot(
    model=model,
    dataset=ds,
    recipe=recipe,
    max_seq_length=MAX_SEQUENCE_LENGTH,
    num_calibration_samples=NUM_CALIBRATION_SAMPLES,
    trust_remote_code_model=True,
    data_collator=glm_data_collator,
    output_dir=SAVE_DIR // This was added by me.
)

processor.save_pretrained(SAVE_DIR) // This was added by me.
```

Please let me know if this is correct way to save the mode.

**Comment by kylesayrs** [comment]
@citrix123 There was a [memory bug](https://github.com/huggingface/transformers/pull/34890) that affected specifically versions `transformers <= 4.46.0` | `accelerate == 1.1.0, 1.1.1`

I'll attempt to replicate on my side, please check the versions of these two libraries on your side.

**Comment by citrix123** [comment]
It seems i have all updated versions.

``` sh
# pip list | grep -E 'accelerate|transformers'
accelerate                        1.2.1
transformers                      4.47.1
```

Is this some other issue ?

**Comment by citrix123** [comment]
Hi @kylesayrs 

Did you got chance to try the scenerio at your side ??

**Comment by kylesayrs** [comment]
@citrix123 Here's my memory allocation graph 

```python3
# text_generation.py
import torch
torch.cuda.memory._record_memory_history()

if isinstance(model_args.model, str) or (
    training_args.output_dir
    != TrainingArguments.__dataclass_fields__["output_dir"].default
):
    model.save_pretrained(
        training_args.output_dir, save_compressed=training_args.save_compressed
    )
    if processor is not None:
        processor.save_pretrained(training_args.output_dir)

torch.cuda.memory._dump_snapshot(f"glm.pickle")
```

![Screenshot 2025-01-07 at 14 08 16](https://github.com/user-attachments/assets/cf877a07-bd83-415b-bc9f-e8bd2f5bfd42)

It seems like saving the model with this pathway only uses an extra ~1gb above the ~2.5gb baseline.

**Comment by kylesayrs** [comment]
Hi @citrix123!

oneshot `outdir` pathway
```python3
# text_generation.py
import torch
torch.cuda.memory._record_memory_history()

if isinstance(model_args.model, str) or (
    training_args.output_dir
    != TrainingArguments.__dataclass_fields__["output_dir"].default
):
    model.save_pretrained(
        training_args.output_dir, save_compressed=training_args.save_compressed
    )
    if processor is not None:
        processor.save_pretrained(training_args.output_dir)

torch.cuda.memory._dump_snapshot(f"glm.pickle")
```
![Screenshot 2025-01-07 at 14 45 29](https://github.com/user-attachments/assets/2fc249ac-6630-4274-b0a3-57d66c4963be)

No oneshot `save_pretrained` pathway
```python3
import torch
torch.cuda.memory._record_memory_history()
model.save_pretrained("asdf")
torch.cuda.memory._dump_snapshot(f"vanilla.pickle")
```
![Screenshot 2025-01-07 at 14 45 46](https://github.com/user-attachments/assets/5bed29ee-949b-4519-9495-70ed7d56591f)


Getting an offloaded model state dict
```python3
import torch
torch.cuda.memory._record_memory_history()
state_dict = get_state_dict_offloaded_model(model)
torch.cuda.memory._dump_snapshot(f"vanilla.pickle")
```
![Screenshot 2025-01-07 at 14 45 59](https://github.com/user-attachments/assets/1dd138c5-431a-4570-ab9e-7b35d2742133)

It's somewhat difficult to see, this chart shows that using the oneshot `outdir` pathway results in an extra 1gb of max memory compared to the no oneshot `save_pretrained` pathway. This is due to `accelerate`'s implementation of `get_state_dict_offloaded_model`.
