### ISSUE TITLE
KeyError with torch.float8_e4m3fn

### ISSUE THREAD

**Issue by Lue-C** [vllm-project/llm-compressor#138]
**Describe the bug**
Hi, I used the llm-compressor quantization script in a Colab notebook, but it gives me an error concerning the torch dtype.

**Expected behavior**
The quantized model should be saved.

**Environment**
python version 3.10
torch==2.4.0+cu124
llmcompressor==0.1.0

I am running the script below on Colab using a L4 GPU.

This is the code
```
from llmcompressor.transformers import SparseAutoModelForCausalLM
from transformers import AutoTokenizer
from llmcompressor.transformers import oneshot
from llmcompressor.modifiers.quantization import QuantizationModifier

MODEL_ID = "Meta-Llama-3.1-8B-Instruct"

model = SparseAutoModelForCausalLM.from_pretrained(
  MODEL_ID, device_map="auto", torch_dtype="auto")
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

# Configure the simple PTQ quantization
recipe = QuantizationModifier(
  targets="Linear", scheme="FP8_DYNAMIC", ignore=["lm_head"])

# Apply the quantization algorithm.
oneshot(model=model, recipe=recipe)

# Save the model.
SAVE_DIR = MODEL_ID.split("/")[1] + "-FP8-Dynamic"
model.save_pretrained(SAVE_DIR)
tokenizer.save_pretrained(SAVE_DIR)
```

And this is the error message:

```
Compressing model: 100% 739/739 [00:11<00:00, 62.10it/s]
Traceback (most recent call last):
  File "/content/compressor.py", line 17, in <module>
    oneshot(model=model, recipe=recipe)
  File "/usr/local/lib/python3.10/dist-packages/llmcompressor/transformers/finetune/text_generation.py", line 76, in oneshot
    main(model_args, data_args, training_args)
  File "/usr/local/lib/python3.10/dist-packages/llmcompressor/transformers/finetune/text_generation.py", line 359, in main
    stage_runner.one_shot()
  File "/usr/local/lib/python3.10/dist-packages/llmcompressor/transformers/finetune/runner.py", line 194, in one_shot
    save_model_and_recipe(
  File "/usr/local/lib/python3.10/dist-packages/llmcompressor/pytorch/model_load/helpers.py", line 110, in save_model_and_recipe
    model.save_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/llmcompressor/transformers/sparsification/compressed_tensors_utils.py", line 126, in save_pretrained_wrapper
    original_save_pretrained.__get__(model, model_class)(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 2793, in save_pretrained
    safe_save_file(shard, os.path.join(save_directory, shard_file), metadata={"format": "pt"})
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 281, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 475, in _flatten
    return {
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 479, in <dictcomp>
    "data": _tobytes(v, k),
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 413, in _tobytes
    bytes_per_item = _SIZE[tensor.dtype]
KeyError: torch.float8_e4m3fn
```

I interpret the error message to be indicating an error with the pytorch version. Is this correct? How can I solve the problem?

Regards

**Comment by mgoin** [comment]
@Lue-C could you please try checking and/or updating your transformers and safetensors versions?

**Comment by markurtz** [comment]
Closing this out due to lack o activity as well as newer versions being released now. If you're still hitting this issue, please feel free to reopen!
