### ISSUE TITLE
RUN python  llm-compressor/examples/quantization_w8a8_fp8/llama3_example.py ERROR

### ISSUE THREAD

**Issue by exceedzhang** [vllm-project/llm-compressor#42]
**Describe the bug**
RUN llm-compressor/examples/quantization_w8a8_fp8$ python llama3_example.py 
save safetensors :KeyError: torch.float8_e4m3fn

**Expected behavior**

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 18.04]:Linux
2. Python version [e.g. 3.7]:3.10
3. LLM Compressor version or commit hash [e.g. 0.1.0, `f7245c8`]:
4. ML framework version(s) [e.g. torch 1.7.1]:2.3.1
5. Other Python package versions [e.g. SparseZoo, DeepSparse, numpy, ONNX]:
6. Other relevant environment information [e.g. hardware, CUDA version]:CUDA 11.8

**To Reproduce**
Exact steps to reproduce the behavior:
RUN llm-compressor/examples/quantization_w8a8_fp8$ python llama3_example.py 

**Errors**
Compressing model: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1187/1187 [00:04<00:00, 256.89it/s]
[2024-07-28 07:33:05,972] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/data1/apps/llm-compressor/examples/quantization_w8a8_fp8/llama3_example.py", line 62, in <module>
    oneshot(
  File "/data1/apps/llm-compressor/src/llmcompressor/transformers/finetune/text_generation.py", line 76, in oneshot
    main(model_args, data_args, training_args)
  File "/data1/apps/llm-compressor/src/llmcompressor/transformers/finetune/text_generation.py", line 358, in main
    stage_runner.one_shot()
  File "/data1/apps/llm-compressor/src/llmcompressor/transformers/finetune/runner.py", line 180, in one_shot
    save_model_and_recipe(
  File "/data1/apps/llm-compressor/src/llmcompressor/pytorch/model_load/helpers.py", line 110, in save_model_and_recipe
    model.save_pretrained(
  File "/data1/apps/llm-compressor/src/llmcompressor/transformers/sparsification/compressed_tensors_utils.py", line 114, in save_pretrained_wrapper
    original_save_pretrained.__get__(model, model_class)(
  File "/data1/apps/miniconda3/envs/Mixtral/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2684, in save_pretrained
    safe_save_file(shard, os.path.join(save_directory, shard_file), metadata={"format": "pt"})
  File "/data1/apps/miniconda3/envs/Mixtral/lib/python3.10/site-packages/safetensors/torch.py", line 281, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
  File "/data1/apps/miniconda3/envs/Mixtral/lib/python3.10/site-packages/safetensors/torch.py", line 475, in _flatten
    return {
  File "/data1/apps/miniconda3/envs/Mixtral/lib/python3.10/site-packages/safetensors/torch.py", line 479, in <dictcomp>
    "data": _tobytes(v, k),
  File "/data1/apps/miniconda3/envs/Mixtral/lib/python3.10/site-packages/safetensors/torch.py", line 413, in _tobytes
    bytes_per_item = _SIZE[tensor.dtype]
KeyError: torch.float8_e4m3fn

**Additional context**
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/e78c96f6-fe3e-46ce-b009-bab6d6f8b43e">

**Comment by exceedzhang** [comment]
![WX20240804-214101@2x](https://github.com/user-attachments/assets/b601f7b8-1157-4d98-8be3-1e90a33b8035)

pip install --upgrade safetensors
