### ISSUE TITLE
[Question]Does Minicpmv2.6 currently support int8 quantization?

### ISSUE THREAD

**Issue by wjj19950828** [vllm-project/llm-compressor#848]
Does Minicpmv2.6 currently support int8 quantization?

thanks~

**Comment by robertgshaw2-neuralmagic** [comment]
We are actively working on support for VLMs, but this is not yet in the current release of `llm-compressor`. We certainly welcome contributions to this effort if you are interested in helping out!

**Comment by mgoin** [comment]
Hi @wjj19950828 currently we have experimental support for dynamic fp8 quantization of VLMs on the main branch

I was able to produce a fp8 dynamic minicpmv2.6 model (https://huggingface.co/nm-testing/MiniCPM-V-2_6-FP8-dynamic) using this script:
```python
from transformers import AutoProcessor, AutoModelForCausalLM

from llmcompressor.modifiers.quantization import QuantizationModifier
from llmcompressor.transformers import oneshot, wrap_hf_model_class

MODEL_ID = "openbmb/MiniCPM-V-2_6"

# Load model.
model_class = wrap_hf_model_class(AutoModelForCausalLM)
model = model_class.from_pretrained(MODEL_ID, torch_dtype="auto", trust_remote_code=True).to("cuda")
processor = AutoProcessor.from_pretrained(MODEL_ID, trust_remote_code=True)

# Configure the quantization algorithm and scheme.
# In this case, we:
#   * quantize the weights to fp8 with per channel via ptq
#   * quantize the activations to fp8 with dynamic per token
recipe = QuantizationModifier(
    targets="Linear",
    scheme="FP8_DYNAMIC",
    ignore=["re:.*lm_head", "re:resampler.*", "re:vpm.*"],
)

# Apply quantization and save to disk in compressed-tensors format.
SAVE_DIR = MODEL_ID.split("/")[1] + "-FP8-dynamic"
oneshot(model=model, recipe=recipe, output_dir=SAVE_DIR, trust_remote_code_model=True)
processor.save_pretrained(SAVE_DIR)
```

It seems to load into vLLM 0.6.3 just fine, but I haven't evaluated the model yet:
```
vllm serve MiniCPM-V-2_6-FP8-dynamic --trust-remote-code
...
INFO 10-17 00:09:51 model_runner.py:1072] Loading model weights took 9.0869 GB
...
INFO:     Uvicorn running on socket ('0.0.0.0', 8000) (Press CTRL+C to quit)
```

**Comment by donpromax** [comment]
I also tried fp8 dynamic for internvl2, it works. But I failed to quantize internvl2 using w8a8-int8.

**Comment by robertgshaw2-neuralmagic** [comment]
Thanks @donpromax - we will share some updates on multimodal in our next release. Closing for now.

**Comment by LSC527** [comment]
> Hi @wjj19950828 currently we have experimental support for dynamic fp8 quantization of VLMs on the main branch
> 
> I was able to produce a fp8 dynamic minicpmv2.6 model (https://huggingface.co/nm-testing/MiniCPM-V-2_6-FP8-dynamic) using this script:
> 
> ```python
> from transformers import AutoProcessor, AutoModelForCausalLM
> 
> from llmcompressor.modifiers.quantization import QuantizationModifier
> from llmcompressor.transformers import oneshot, wrap_hf_model_class
> 
> MODEL_ID = "openbmb/MiniCPM-V-2_6"
> 
> # Load model.
> model_class = wrap_hf_model_class(AutoModelForCausalLM)
> model = model_class.from_pretrained(MODEL_ID, torch_dtype="auto", trust_remote_code=True).to("cuda")
> processor = AutoProcessor.from_pretrained(MODEL_ID, trust_remote_code=True)
> 
> # Configure the quantization algorithm and scheme.
> # In this case, we:
> #   * quantize the weights to fp8 with per channel via ptq
> #   * quantize the activations to fp8 with dynamic per token
> recipe = QuantizationModifier(
>     targets="Linear",
>     scheme="FP8_DYNAMIC",
>     ignore=["re:.*lm_head", "re:resampler.*", "re:vpm.*"],
> )
> 
> # Apply quantization and save to disk in compressed-tensors format.
> SAVE_DIR = MODEL_ID.split("/")[1] + "-FP8-dynamic"
> oneshot(model=model, recipe=recipe, output_dir=SAVE_DIR, trust_remote_code_model=True)
> processor.save_pretrained(SAVE_DIR)
> ```
> 
> It seems to load into vLLM 0.6.3 just fine, but I haven't evaluated the model yet:
> 
> ```
> vllm serve MiniCPM-V-2_6-FP8-dynamic --trust-remote-code
> ...
> INFO 10-17 00:09:51 model_runner.py:1072] Loading model weights took 9.0869 GB
> ...
> INFO:     Uvicorn running on socket ('0.0.0.0', 8000) (Press CTRL+C to quit)
> ```

I run quantization on NVIDIA A30 24G, and serve the quantized model on A30 24G works fine. 
But when I try to serve the quantized model on A30 MIG 12G, an error happens:
```python
ERROR 12-13 10:44:23 engine.py:366] Traceback (most recent call last):
ERROR 12-13 10:44:23 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner_base.py", line 116, in _wrapper
ERROR 12-13 10:44:23 engine.py:366]     return func(*args, **kwargs)
ERROR 12-13 10:44:23 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 1654, in execute_model
ERROR 12-13 10:44:23 engine.py:366]     hidden_or_intermediate_states = model_executable(
ERROR 12-13 10:44:23 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
ERROR 12-13 10:44:23 engine.py:366]     return self._call_impl(*args, **kwargs)
ERROR 12-13 10:44:23 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
ERROR 12-13 10:44:23 engine.py:366]     return forward_call(*args, **kwargs)
ERROR 12-13 10:44:23 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/minicpmv.py", line 571, in forward
ERROR 12-13 10:44:23 engine.py:366]     vlm_embeddings, _ = self.get_embedding(input_ids, image_inputs)
ERROR 12-13 10:44:23 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/minicpmv.py", line 442, in get_embedding
ERROR 12-13 10:44:23 engine.py:366]     vision_hidden_states = self.get_vision_hidden_states(
ERROR 12-13 10:44:23 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/minicpmv.py", line 1068, in get_vision_hidden_states
ERROR 12-13 10:44:23 engine.py:366]     vision_embedding = self.vpm(
ERROR 12-13 10:44:23 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
ERROR 12-13 10:44:23 engine.py:366]     return self._call_impl(*args, **kwargs)
ERROR 12-13 10:44:23 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
ERROR 12-13 10:44:23 engine.py:366]     return forward_call(*args, **kwargs)
ERROR 12-13 10:44:23 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/idefics2_vision_model.py", line 326, in forward
ERROR 12-13 10:44:23 engine.py:366]     hidden_states = self.embeddings(
ERROR 12-13 10:44:23 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
ERROR 12-13 10:44:23 engine.py:366]     return self._call_impl(*args, **kwargs)
ERROR 12-13 10:44:23 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
ERROR 12-13 10:44:23 engine.py:366]     return forward_call(*args, **kwargs)
ERROR 12-13 10:44:23 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/idefics2_vision_model.py", line 72, in forward
ERROR 12-13 10:44:23 engine.py:366]     patch_embeds = self.patch_embedding(pixel_values)
ERROR 12-13 10:44:23 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
ERROR 12-13 10:44:23 engine.py:366]     return self._call_impl(*args, **kwargs)
ERROR 12-13 10:44:23 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
ERROR 12-13 10:44:23 engine.py:366]     return forward_call(*args, **kwargs)
ERROR 12-13 10:44:23 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 554, in forward
ERROR 12-13 10:44:23 engine.py:366]     return self._conv_forward(input, self.weight, self.bias)
ERROR 12-13 10:44:23 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 549, in _conv_forward
ERROR 12-13 10:44:23 engine.py:366]     return F.conv2d(
ERROR 12-13 10:44:23 engine.py:366] RuntimeError: NVML_SUCCESS == r INTERNAL ASSERT FAILED at "../c10/cuda/CUDACachingAllocator.cpp":995, please report a bug to PyTorch.
```
Is this normal?
