### ISSUE TITLE
Qwen2VL FP8_DYNAMIC Failed

### ISSUE THREAD

**Issue by LugerW-A** [vllm-project/llm-compressor#951]
When I use the example code to quant Qwen2VL. It can run successfully, but the number of safetensors for the generated model parameters remains the same, and the size of each safetensor does not change. It also fails to load successfully using vllm.

vllm:
[rank0]: Traceback (most recent call last):
[rank0]:   File "/mnt/bn/vllmlfdata/deploymultitokens_place_TEST/handlerfp8.py", line 125, in <module>
[rank0]:     handler = EndpointHandler()
[rank0]:               ^^^^^^^^^^^^^^^^^
[rank0]:   File "/mnt/bn/vllmlfdata/deploymultitokens_place_TEST/handlerfp8.py", line 42, in __init__
[rank0]:     self.llm = LLM(MODEL_PATH, 
[rank0]:                ^^^^^^^^^^^^^^^
[rank0]:   File "/home/tiger/.local/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 178, in __init__
[rank0]:     self.llm_engine = LLMEngine.from_engine_args(
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/tiger/.local/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 550, in from_engine_args
[rank0]:     engine = cls(
[rank0]:              ^^^^
[rank0]:   File "/home/tiger/.local/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 317, in __init__
[rank0]:     self.model_executor = executor_class(
[rank0]:                           ^^^^^^^^^^^^^^^
[rank0]:   File "/home/tiger/.local/lib/python3.11/site-packages/vllm/executor/distributed_gpu_executor.py", line 26, in __init__
[rank0]:     super().__init__(*args, **kwargs)
[rank0]:   File "/home/tiger/.local/lib/python3.11/site-packages/vllm/executor/executor_base.py", line 47, in __init__
[rank0]:     self._init_executor()
[rank0]:   File "/home/tiger/.local/lib/python3.11/site-packages/vllm/executor/multiproc_gpu_executor.py", line 125, in _init_executor
[rank0]:     self._run_workers("load_model",
[rank0]:   File "/home/tiger/.local/lib/python3.11/site-packages/vllm/executor/multiproc_gpu_executor.py", line 199, in _run_workers
[rank0]:     driver_worker_output = driver_worker_method(*args, **kwargs)
[rank0]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/tiger/.local/lib/python3.11/site-packages/vllm/worker/worker.py", line 183, in load_model
[rank0]:     self.model_runner.load_model()
[rank0]:   File "/home/tiger/.local/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 999, in load_model
[rank0]:     self.model = get_model(model_config=self.model_config,
[rank0]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/tiger/.local/lib/python3.11/site-packages/vllm/model_executor/model_loader/__init__.py", line 19, in get_model
[rank0]:     return loader.load_model(model_config=model_config,
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/tiger/.local/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py", line 361, in load_model
[rank0]:     model.load_weights(
[rank0]:   File "/home/tiger/.local/lib/python3.11/site-packages/vllm/model_executor/models/qwen2_vl.py", line 1061, in load_weights
[rank0]:     param = params_dict[name]
[rank0]:             ~~~~~~~~~~~^^^^^^
[rank0]: KeyError: 'model.layers.0.mlp.gate_up_proj.weight_scale'

**Comment by LugerW-A** [comment]
Example output:
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████| 31/31 [12:25<00:00, 24.05s/it]
2024-12-04T14:25:06.922124+0800 | main | WARNING - Process rank: 0, device: cuda:0, n_gpu: 4, distributed training: True, 16-bits training: False
2024-12-04T14:25:06.922714+0800 | main | INFO - Training/evaluation parameters TrainingArguments(
_n_gpu=4,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
clear_sparse_session=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
dispatch_batches=None,
do_eval=False,
do_oneshot=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.NO,
eval_use_gather_object=False,
evaluation_strategy=None,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
include_num_input_tokens_seen=False,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
load_best_model_at_end=False,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=/mnt/bn/vllmlfdata/models/Valley-Qwen2-VL-72B-Instruct-1t2k-FP8-Dynamic-llmcompressor/runs/Dec04_14-25-06_g340-cd51-4600-a41e-2b58-ce90-fa00,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=None,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=3.0,
oneshot_device=cuda:0,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=/mnt/bn/vllmlfdata/models/Valley-Qwen2-VL-72B-Instruct-1t2k-FP8-Dynamic-llmcompressor,
overwrite_output_dir=False,
past_index=-1,
per_device_eval_batch_size=8,
per_device_train_batch_size=8,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
recipe=index=None group=None start=None end=None update=None initialized_structure_=False initialized_=False finalized_=False started_=False ended_=False config_groups=None ignore=['re:.*lm_head', 're:visual.*'] targets='Linear' scheme='FP8_DYNAMIC' kv_cache_scheme=None disable_quantization_observer_epoch=None num_calibration_steps=None calibration_dataloader_=None calibration_function_=None calibration_hooks_=None,
recipe_args=None,
remove_unused_columns=True,
report_to=['wandb'],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=/mnt/bn/vllmlfdata/models/Valley-Qwen2-VL-72B-Instruct-1t2k-FP8-Dynamic-llmcompressor,
run_stages=False,
save_compressed=True,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=IntervalStrategy.STEPS,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
split_batches=None,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_cpu=False,
use_ipex=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.0,
warmup_steps=0,
weight_decay=0.0,
)
2024-12-04T14:25:07.151883+0800 | _check_create_state | INFO - State created for compression lifecycle
2024-12-04T14:25:07.153866+0800 | pre_initialize_structure | INFO - Compression lifecycle structure pre-initialized for 0 modifiers
2024-12-04T14:25:07.153991+0800 | pre_initialize_structure | INFO - Compression lifecycle structure pre-initialized for 0 modifiers
2024-12-04T14:25:07.154055+0800 | populate_datasets | INFO - Running oneshot without calibration data. This is expected for weight-only and dynamic quantization
Detected kernel version 5.4.143, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
/home/tiger/.local/lib/python3.11/site-packages/bytedmetrics/__init__.py:10: UserWarning: bytedmetrics is renamed to bytedance.metrics, please using `bytedance.metrics` instead of `bytedmetrics`
  warnings.warn("bytedmetrics is renamed to bytedance.metrics, please using `bytedance.metrics` instead of `bytedmetrics`")
2024-12-04T14:25:07.386838+0800 | one_shot | INFO - *** One Shot ***
2024-12-04T14:25:07.387237+0800 | from_modifiers | INFO - Creating recipe from modifiers
2024-12-04T14:25:07.416408+0800 | _check_compile_recipe | INFO - Recipe compiled and 1 modifiers created
manager stage: Modifiers initialized
2024-12-04T14:25:08.068029+0800 | initialize | INFO - Compression lifecycle initialized for 1 modifiers
manager stage: Modifiers finalized
2024-12-04T14:25:08.068266+0800 | finalize | INFO - Compression lifecycle finalized for 1 modifiers
2024-12-04T14:32:02.322802+0800 | save_model_and_recipe | INFO - Saving output to /mnt/bn/vllmlfdata/models/Valley-Qwen2-VL-72B-Instruct-1t2k-FP8-Dynamic-llmcompressor
========== SAMPLE GENERATION ==============
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Hello my name is Kaitlyn and I am a 20 year old female. I have been babysitting for
==========================================

**Comment by PeterWang1986** [comment]
we met the same issue for Meta-Llama-3-8B-Instruct
GPU: A100-40G, llm-compressor: 0.3.0, vllm: 0.6.4.post1

**Comment by dsikka** [comment]
Hi @LugerW-A it looks like the model isn't compressing after being quantized. Can you share what version of llm-compressor and compressed-tensors you're using?

**Comment by LugerW-A** [comment]
> Hi @LugerW-A it looks like the model isn't compressing after being quantized. Can you share what version of llm-compressor and compressed-tensors you're using?

Thank you.
GPU: L20 llm-compressor: 0.3.0 compressed-tensors:0.8.0

**Comment by LugerW-A** [comment]
> we met the same issue for Meta-Llama-3-8B-Instruct / Meta-Llama-3.1-8B-Instruct GPU: A100-40G, llm-compressor: 0.3.0, vllm: 0.6.4.post1

Hi Did you solve it?

**Comment by hestabit-dev** [comment]
Did anyone solved this issue?

**Comment by kylesayrs** [comment]
Hi all, you can quantize vision models reliably using the `kylesayrs/gptq-partition` and running `python3 examples/multimodal_vision/qwen.py`. Please modify the scheme to reflect FP8 quantization. This pathway is untested for FP8, but it may prove to be more reliable.

**Comment by PeterWang1986** [comment]
> > we met the same issue for Meta-Llama-3-8B-Instruct / Meta-Llama-3.1-8B-Instruct GPU: A100-40G, llm-compressor: 0.3.0, vllm: 0.6.4.post1
> 
> Hi Did you solve it?

No, currently we load it by using vllm with --quantization=fp8 as a workaround

**Comment by LugerW-A** [comment]
> > > we met the same issue for Meta-Llama-3-8B-Instruct / Meta-Llama-3.1-8B-Instruct GPU: A100-40G, llm-compressor: 0.3.0, vllm: 0.6.4.post1
> > 
> > 
> > Hi Did you solve it?
> 
> No, currently we load it by using vllm with --quantization=fp8 as a workaround

Hi.Is there any difference between these two? How is the performance?

**Comment by kylesayrs** [comment]
I have run the qwen2_vl example and verified that this is resolved, although there issues separate to this one related to running with vllm as of the latest transformers release. I will link when that issue is opened
