### ISSUE TITLE
KeyError: 'model.layers.0.self_attn.k_scale'

### ISSUE THREAD

**Issue by wxsms** [vllm-project/llm-compressor#967]
**Describe the bug**
Quantize a starcoder2 model follow: https://github.com/vllm-project/llm-compressor/blob/0.3.0/examples/quantization_kv_cache/llama3_fp8_kv_example.py

then serve with vllm

**Expected behavior**
work normally

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 20.04]: Ubuntu 22.04
2. Python version [e.g. 3.7]: 3.10
3. LLM Compressor version or commit hash [e.g. 0.1.0, `f7245c8`]: 0.3.0
4. ML framework version(s) [e.g. torch 2.3.1]: torch 2.5.1
5. Other Python package versions [e.g. vLLM, compressed-tensors, numpy, ONNX]: vllm 0.6.4.post1
6. Other relevant environment information [e.g. hardware, CUDA version]: 4090, cu121

**To Reproduce**
just follow the official example code to quantize a starcoder2 14b model then serve

**Errors**

```
WARNING 12-10 15:39:25 cuda.py:23] You are using a deprecated `pynvml` package. Please install `nvidia-ml-py` instead, and make sure to uninstall `pynvml`. When both of them are installed, `pynvml` will take precedence and cause errors. See https://pypi.org/project/pynvml for more information.
INFO 12-10 15:39:27 api_server.py:585] vLLM API server version 0.6.4.post1
INFO 12-10 15:39:27 api_server.py:586] args: Namespace(subparser='serve', model_tag='/mnt/models/target/fp8_static', config='', host=None, port=9000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_auto_tool_choice=False, tool_call_parser=None, tool_parser_plugin='', model='/mnt/models/target/fp8_static', task='auto', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', chat_template_text_format='string', trust_remote_code=False, allowed_local_media_path=None, download_dir=None, load_format='auto', config_format=<ConfigFormat.AUTO: 'auto'>, dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=4096, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=128, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, hf_overrides=None, enforce_eager=False, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, mm_processor_kwargs=None, enable_lora=False, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, multi_step_stream_outputs=True, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_disable_mqa_scorer=False, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=['starcoder'], qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, scheduling_policy='fcfs', override_neuron_config=None, override_pooler_config=None, disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, enable_prompt_tokens_details=False, dispatch_function=<function serve at 0x7f2539144b80>)
INFO 12-10 15:39:27 api_server.py:175] Multiprocessing frontend to use ipc:///tmp/96f14d3b-98a3-4595-84d2-87e171cbc608 for IPC Path.
INFO 12-10 15:39:27 api_server.py:194] Started engine process with PID 264032
WARNING 12-10 15:39:29 cuda.py:23] You are using a deprecated `pynvml` package. Please install `nvidia-ml-py` instead, and make sure to uninstall `pynvml`. When both of them are installed, `pynvml` will take precedence and cause errors. See https://pypi.org/project/pynvml for more information.
WARNING 12-10 15:39:31 arg_utils.py:1075] [DEPRECATED] Block manager v1 has been removed, and setting --use-v2-block-manager to True or False has no effect on vLLM behavior. Please remove --use-v2-block-manager in your engine argument. If your use case is not supported by SelfAttnBlockSpaceManager (i.e. block manager v2), please file an issue with detailed information.
WARNING 12-10 15:39:35 arg_utils.py:1075] [DEPRECATED] Block manager v1 has been removed, and setting --use-v2-block-manager to True or False has no effect on vLLM behavior. Please remove --use-v2-block-manager in your engine argument. If your use case is not supported by SelfAttnBlockSpaceManager (i.e. block manager v2), please file an issue with detailed information.
INFO 12-10 15:39:35 llm_engine.py:249] Initializing an LLM engine (v0.6.4.post1) with config: model='/mnt/models/target/fp8_static', speculative_config=None, tokenizer='/mnt/models/target/fp8_static', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=compressed-tensors, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=starcoder, num_scheduler_steps=1, chunked_prefill_enabled=False multi_step_stream_outputs=True, enable_prefix_caching=False, use_async_output_proc=True, use_cached_outputs=True, chat_template_text_format=string, mm_processor_kwargs=None, pooler_config=None)
INFO 12-10 15:39:35 selector.py:135] Using Flash Attention backend.
INFO 12-10 15:39:36 model_runner.py:1072] Starting to load model /mnt/models/target/fp8_static...
Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
ERROR 12-10 15:39:36 engine.py:366] 'model.layers.0.self_attn.k_scale'
ERROR 12-10 15:39:36 engine.py:366] Traceback (most recent call last):
ERROR 12-10 15:39:36 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/multiprocessing/engine.py", line 357, in run_mp_engine
ERROR 12-10 15:39:36 engine.py:366]     engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
ERROR 12-10 15:39:36 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/multiprocessing/engine.py", line 119, in from_engine_args
ERROR 12-10 15:39:36 engine.py:366]     return cls(ipc_path=ipc_path,
ERROR 12-10 15:39:36 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/multiprocessing/engine.py", line 71, in __init__
ERROR 12-10 15:39:36 engine.py:366]     self.engine = LLMEngine(*args, **kwargs)
ERROR 12-10 15:39:36 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 347, in __init__
ERROR 12-10 15:39:36 engine.py:366]     self.model_executor = executor_class(vllm_config=vllm_config, )
ERROR 12-10 15:39:36 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/executor_base.py", line 36, in __init__
ERROR 12-10 15:39:36 engine.py:366]     self._init_executor()
ERROR 12-10 15:39:36 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/gpu_executor.py", line 40, in _init_executor
ERROR 12-10 15:39:36 engine.py:366]     self.driver_worker.load_model()
ERROR 12-10 15:39:36 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 152, in load_model
ERROR 12-10 15:39:36 engine.py:366]     self.model_runner.load_model()
ERROR 12-10 15:39:36 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 1074, in load_model
ERROR 12-10 15:39:36 engine.py:366]     self.model = get_model(vllm_config=self.vllm_config)
ERROR 12-10 15:39:36 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader/__init__.py", line 12, in get_model
ERROR 12-10 15:39:36 engine.py:366]     return loader.load_model(vllm_config=vllm_config)
ERROR 12-10 15:39:36 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader/loader.py", line 334, in load_model
ERROR 12-10 15:39:36 engine.py:366]     model.load_weights(self._get_all_weights(model_config, model))
ERROR 12-10 15:39:36 engine.py:366]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/starcoder2.py", line 333, in load_weights
ERROR 12-10 15:39:36 engine.py:366]     param = params_dict[name]
ERROR 12-10 15:39:36 engine.py:366] KeyError: 'model.layers.0.self_attn.k_scale'
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/multiprocessing/engine.py", line 368, in run_mp_engine
    raise e
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/multiprocessing/engine.py", line 357, in run_mp_engine
    engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/multiprocessing/engine.py", line 119, in from_engine_args
    return cls(ipc_path=ipc_path,
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/multiprocessing/engine.py", line 71, in __init__
    self.engine = LLMEngine(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 347, in __init__
    self.model_executor = executor_class(vllm_config=vllm_config, )
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/executor_base.py", line 36, in __init__
    self._init_executor()
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/gpu_executor.py", line 40, in _init_executor
    self.driver_worker.load_model()
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 152, in load_model
    self.model_runner.load_model()
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 1074, in load_model
    self.model = get_model(vllm_config=self.vllm_config)
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader/__init__.py", line 12, in get_model
    return loader.load_model(vllm_config=vllm_config)
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader/loader.py", line 334, in load_model
    model.load_weights(self._get_all_weights(model_config, model))
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/starcoder2.py", line 333, in load_weights
    param = params_dict[name]
KeyError: 'model.layers.0.self_attn.k_scale'
```

**Additional context**
similar to #959  maybe?

**Comment by dsikka** [comment]
Hi @wxsms can you share a config of the model you're trying to run?

**Comment by wxsms** [comment]
Before quantize:

```json
{
  "architectures": [
    "Starcoder2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 0,
  "embedding_dropout": 0.0,
  "eos_token_id": 0,
  "hidden_act": "gelu_pytorch_tanh",
  "hidden_size": 6144,
  "initializer_range": 0.01275,
  "intermediate_size": 24576,
  "max_position_embeddings": 16384,
  "mlp_type": "default",
  "model_type": "starcoder2",
  "norm_epsilon": 1e-05,
  "norm_type": "layer_norm",
  "num_attention_heads": 48,
  "num_hidden_layers": 40,
  "num_key_value_heads": 4,
  "residual_dropout": 0.0,
  "rms_norm_eps": 1e-05,
  "rope_theta": 100000,
  "sliding_window": 4096,
  "tie_word_embeddings": false,
  "torch_dtype": "float32",
  "transformers_version": "4.40.1",
  "use_bias": true,
  "use_cache": false,
  "vocab_size": 49152
}
```

After quantize:

```json
{
  "_name_or_path": "/mnt/models/source",
  "architectures": [
    "Starcoder2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 0,
  "embedding_dropout": 0.0,
  "eos_token_id": 0,
  "hidden_act": "gelu_pytorch_tanh",
  "hidden_size": 6144,
  "initializer_range": 0.01275,
  "intermediate_size": 24576,
  "max_position_embeddings": 16384,
  "mlp_type": "default",
  "model_type": "starcoder2",
  "norm_epsilon": 1e-05,
  "norm_type": "layer_norm",
  "num_attention_heads": 48,
  "num_hidden_layers": 40,
  "num_key_value_heads": 4,
  "quantization_config": {
    "config_groups": {
      "group_0": {
        "input_activations": {
          "actorder": null,
          "block_structure": null,
          "dynamic": false,
          "group_size": null,
          "num_bits": 8,
          "observer": "minmax",
          "observer_kwargs": {},
          "strategy": "tensor",
          "symmetric": true,
          "type": "float"
        },
        "output_activations": null,
        "targets": [
          "Linear"
        ],
        "weights": {
          "actorder": null,
          "block_structure": null,
          "dynamic": false,
          "group_size": null,
          "num_bits": 8,
          "observer": "minmax",
          "observer_kwargs": {},
          "strategy": "tensor",
          "symmetric": true,
          "type": "float"
        }
      }
    },
    "format": "float-quantized",
    "global_compression_ratio": 1.4225352022277455,
    "ignore": [
      "lm_head"
    ],
    "kv_cache_scheme": {
      "actorder": null,
      "block_structure": null,
      "dynamic": false,
      "group_size": null,
      "num_bits": 8,
      "observer": "minmax",
      "observer_kwargs": {},
      "strategy": "tensor",
      "symmetric": true,
      "type": "float"
    },
    "quant_method": "compressed-tensors",
    "quantization_status": "compressed"
  },
  "residual_dropout": 0.0,
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "rope_theta": 100000,
  "sliding_window": 4096,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.47.0",
  "use_bias": true,
  "use_cache": false,
  "vocab_size": 49152
}
```

**Comment by wxsms** [comment]
```python
from datasets import load_dataset,load_from_disk
from loguru import logger
from transformers import AutoModelForCausalLM, AutoTokenizer

from llmcompressor.transformers import oneshot, SparseAutoModelForCausalLM

# Select model and load it.
MODEL_ID = "/mnt/models/source"
model = SparseAutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    device_map="auto",
    torch_dtype="bfloat16",
)
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

# Select calibration dataset.
# DATASET_ID = "HuggingFaceH4/ultrachat_200k"
# DATASET_SPLIT = "train_sft"

# Select number of samples. 512 samples is a good place to start.
# Increasing the number of samples can improve accuracy.
NUM_CALIBRATION_SAMPLES = 512
MAX_SEQUENCE_LENGTH = 4096

# Load dataset and preprocess.
# ds = load_dataset(DATASET_ID, split=DATASET_SPLIT)
ds = load_from_disk('/data/script/datasets/cnn_dailymail')
ds = ds.shuffle(seed=42).select(range(NUM_CALIBRATION_SAMPLES))


def process_and_tokenize(example):
    # print(11111, example)
    # text = tokenizer.apply_chat_template(example["article"], tokenize=False)
    return tokenizer(
        example["article"],
        padding=False,
        max_length=MAX_SEQUENCE_LENGTH,
        truncation=True,
        add_special_tokens=False,
    )


ds = ds.map(process_and_tokenize, remove_columns=ds.column_names)

# Configure the quantization algorithm and scheme.
# In this case, we:
#   * quantize the weights to fp8 with per-tensor scales
#   * quantize the activations to fp8 with per-tensor scales
#   * quantize the kv cache to fp8 with per-tensor scales
recipe = """
quant_stage:
    quant_modifiers:
        QuantizationModifier:
            ignore: ["lm_head"]
            config_groups:
                group_0:
                    weights:
                        num_bits: 8
                        type: float
                        strategy: tensor
                        dynamic: false
                        symmetric: true
                    input_activations:
                        num_bits: 8
                        type: float
                        strategy: tensor
                        dynamic: false
                        symmetric: true
                    targets: ["Linear"]
            kv_cache_scheme:
                num_bits: 8
                type: float
                strategy: tensor
                dynamic: false
                symmetric: true
"""

# Apply algorithms.
oneshot(
    model=model,
    dataset=ds,
    recipe=recipe,
    max_seq_length=MAX_SEQUENCE_LENGTH,
    num_calibration_samples=NUM_CALIBRATION_SAMPLES,
)

# Confirm generations of the quantized model look sane.
# print("\n\n")
# print("========== SAMPLE GENERATION ==============")
# input_ids = tokenizer("Hello my name is", return_tensors="pt").input_ids.to("cuda")
# output = model.generate(input_ids, max_new_tokens=100)
# print(tokenizer.decode(output[0]))
# print("==========================================\n\n")

# Save to disk compressed.
SAVE_DIR = "/mnt/models/target/fp8_static"
model.save_pretrained(SAVE_DIR, save_compressed=True)
tokenizer.save_pretrained(SAVE_DIR)

```

then serve:

```
set -ex

args=(
  /mnt/models/target/fp8_static
  --served-model-name starcoder
  --max-model-len 4096
  --port 9000
  --max-num-seqs 128

)

vllm serve  "${args[@]}"
```

**Comment by matthew-hippocratic** [comment]
Getting the same type of error (I quantized with the same exact recipe)

**Comment by dsikka** [comment]
@wxsms: https://github.com/vllm-project/vllm/pull/11148

**Comment by wxsms** [comment]
Thank you for the very quick response!
